## Parte 1: Forward Progation

Igorando el sesgo/bias y asumiendo activación sigmoidal implementar la siguiente red neuronal en NumPy

https://gadictos.com/neural-network-pt1/
<img src="https://gadictos.com/wp-content/uploads/2019/05/bp1.png">

In [1]:
import numpy as np

In [2]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

sigmoid(np.array([2,3,4]))

array([0.88079708, 0.95257413, 0.98201379])

In [3]:
Wc1 = np.array([
   [0.9,0.3,0.2],
   [0.8,0.5,0.4],
   [0.1,0.6,0.7]
])

In [4]:
Wc2 = np.array([0.3,0.5,0.9])

In [5]:
# 4 observaciones, 3 variables
X = np.array([
      [1,0,1],
      [1,2,3],
      [4,5,6],
      [6,7,8],
])

### Forward-propagation(inferencia, prediccion, o estimacion)


In [6]:
H = np.matmul(X, Wc1)

In [7]:
X.shape

(4, 3)

In [8]:
Wc1.shape

(3, 3)

In [9]:
H.shape

(4, 3)

In [10]:
H

array([[ 1. ,  0.9,  0.9],
       [ 2.8,  3.1,  3.1],
       [ 8.2,  7.3,  7. ],
       [11.8, 10.1,  9.6]])

In [11]:
A = sigmoid(H)

In [12]:
A

array([[0.73105858, 0.7109495 , 0.7109495 ],
       [0.94267582, 0.95689275, 0.95689275],
       [0.99972542, 0.99932492, 0.99908895],
       [0.9999925 , 0.99995892, 0.99993228]])

In [13]:
y_aprox = sigmoid(np.matmul(
    A,Wc2
))

In [14]:
y_aprox

array([0.77112013, 0.83513309, 0.84537273, 0.8455238 ])

In [16]:
def g(X):
    return sigmoid(np.matmul(X,Wc1))

In [17]:
def f(g):
    return sigmoid(np.matmul(g,Wc2))

In [18]:
y_aprox = f(g(X))

In [19]:
y_aprox

array([0.77112013, 0.83513309, 0.84537273, 0.8455238 ])

#### Orientado a objetos

In [33]:
# 4 observaciones, 3 variables
X = np.array([
      [1,0,1],
      [1,2,3],
      [4,5,6],
      [6,7,8],
])

In [36]:
class RedNeuronal:
    def __init__(self):
        self.Wc1 = np.array([
           [0.9,0.3,0.2],
           [0.8,0.5,0.4],
           [0.1,0.6,0.7]])
        self. Wc2  = np.array([0.3,0.5,0.9])
        
    def sigmoid(self, X):
        return 1/(1+np.exp(-X))

    def forward_propagation(self, X):
        A = self.sigmoid(np.matmul(X, self.Wc1))
        y_aprox = self.sigmoid(np.matmul(A, self.Wc2))

        return y_aprox

In [37]:
red = RedNeuronal()
red.forward_propagation(X) 

array([0.77112013, 0.83513309, 0.84537273, 0.8455238 ])

<img src="https://i.imgur.com/IDFRq5a.png">

[0.73105858 0.78583498 0.68997448]

In [22]:
class RedNeuronal:
    def __init__(self):
        self.Wc1 = np.array([
            [0.8,0.2],
            [0.4,0.9],
            [0.3,0.5]    
        ])

        self. Wc2  = np.array([0.3,0.5,0.9])

    def forward_propagation(self,X):
        A = sigmoid(np.matmul(X,self.Wc1.T)) 
        y_aprox = sigmoid(np.matmul(A,self.Wc2))
        return y_aprox

In [23]:
# 4 observaciones, 2 variables
X = np.array([
      [1,1],
      [1,2],
      [4,5],
      [6,7],
])

In [24]:
red = RedNeuronal()
y_aprox = red.forward_propagation(X)

(4, 2)
(2, 3)
[[0.73105858 0.78583498 0.68997448]
 [0.76852478 0.90024951 0.78583498]
 [0.98522597 0.99776215 0.97587298]
 [0.99797468 0.99983344 0.9950332 ]]
(4, 3)
(4,)


In [25]:
y_aprox

array([0.77438027, 0.80026216, 0.84194007, 0.84485948])

<img src="ejercicio3.png">

In [88]:
class RedNeuronal:
    def __init__(self):
        self.Wc1 = np.array([
            [5, 7],
            [-2, -3],
            [-8, 1]    
        ])

        self.Wc2  = np.array([7, 5, -6])
        
    def sigmoid(self, X):
        return 1/(1+np.exp(-X))

    def forward_propagation(self, X):
        A = self.sigmoid(np.matmul(X, self.Wc1))
        inter = np.ones((A.shape[0], 3))
        inter[:, :2] = A
        return self.sigmoid(np.matmul(inter, self.Wc2))

In [89]:

X = np.array([
      [1,1,1],
      [1,2,1],
      [4,5,1],
      [6,7,1],
])

In [90]:
red = RedNeuronal()
y_aprox = red.forward_propagation(X)

In [91]:
y_aprox

array([0.27158134, 0.16943494, 0.99432264, 0.99752158])

## Parte 2: Calculo de parametros para las siguientes redes

<img src="e1.png">
Asumiendo que no tiene bias, unicamente son 3 parametros.

<img src="e2.png">

Ya que explicitamente menciona el bias, seria 3 parametros.
<img src="e3.png">
Asumiendo que no tiene bias, son 12 parametros.

<img src="e4.png">

Ya que explicitamente menciona el bias, serian 9 parametros.
<img src="e5.png">

Asumiendo que no tiene bias, son 10 parametros.
<img src="e6.png">

Asumiendo que no tiene bias, son 20 parametros.